name: Build Test
on:
  push:

jobs:
  tests:
    name: Test Download
    runs-on: windows-latest
    env:
      CHERE_INVOKING : 'yes'
      MSYSTEM : 'MINGW64'
    steps:
      - uses: actions/checkout@v2
      - name: Install msys2
        run: |
          powershell "C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-ttf-dejavu --noconfirm'"
          $env:PATH += ";C:\msys64\mingw64\bin;C:\msys64\usr\bin"
          echo "::set-env name=PATH::$env:PATH"
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build
        run: |
          cp .github/download_binaries.py download_binaries.py
          pip install certifi
          python download_binaries.py 64
          tree /F /A build/local
      - name: Build
        uses: actions/upload-artifact@v2
        with:
          name: build-test
          path: build/local
