name: Build Test
on:
  push:

jobs:
  tests:
    name: Test Download
    runs-on: windows-latest
    env:
      CHERE_INVOKING : 'yes'
      MSYSTEM : 'MINGW64'
    steps:
      - uses: actions/checkout@v2
      - name: Install msys2
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://github.com/msys2/msys2-installer/releases/download/2020-06-29/msys2-base-x86_64-20200629.sfx.exe', 'msys2.exe')
          .\msys2.exe -y -oC:\  # Extract to C:\msys64
          Remove-Item msys2.exe
          powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-ttf-dejavu --noconfirm'"
          $env:PATH += ";C:\tools\msys64\mingw64\bin;C:\tools\msys64\usr\bin"
          echo "::set-env name=PATH::$env:PATH"
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build
        run: |
          cp .github/download_binaries.py download_binaries.py
          python download_binaries.py 64
          tree /F /A build
      - name: Build
        uses: actions/upload-artifact@v2
        with:
          name: build-test
          path: build
