name: WeasyPrint's tests
on: [push]

jobs:
  tests:
    name: ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
          # Pillow wheel missing for this configuration
          - os: macos-latest
            python-version: pypy3
          # Cannot find installed libraries
          - os: windows-latest
            python-version: pypy3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install DejaVu (Ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get update -y && sudo apt-get install fonts-dejavu -y
      - name: Install DejaVu, Pango, libffi and Ghostscript (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew tap homebrew/cask-fonts
          brew cask install font-dejavu
          brew install pango libffi ghostscript
      - name: Install DejaVu, Pango and Ghostscript (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-ttf-dejavu mingw-w64-x86_64-pango mingw-w64-x86_64-ghostscript --noconfirm'
          xcopy "C:\msys64\mingw64\share\fonts\TTF" "C:\Users\runneradmin\.fonts" /e /i
          echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH
          rm C:\msys64\mingw64\bin\python.exe
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install pydyf
        run: python -m pip install git+https://github.com/CourtBouillon/pydyf.git
      - name: Upgrade cffi (Windows)
        if: matrix.os == 'windows-latest'
        run: python -m pip install --upgrade cffi
      - name: Launch tests
        run: pytest
